-- MySQL Script generated by MySQL Workbench
-- lun. 11 févr. 2019 14:41:38 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ngshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ngshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngshop` DEFAULT CHARACTER SET latin1 ;
USE `ngshop` ;

-- -----------------------------------------------------
-- Table `ngshop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`categories` (
  `id_categories` INT NOT NULL AUTO_INCREMENT,
  `categories_label` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngshop`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`produits` (
  `id_produits` INT NOT NULL AUTO_INCREMENT,
  `produits_label` VARCHAR(100) NULL,
  `produits_poids` INT NULL,
  `produits_desc` VARCHAR(45) NULL,
  `produits_prix` DECIMAL(5,2) NULL,
  `produits_stock` INT NULL,
  `produits_url_img` VARCHAR(256) NULL,
  `categories_id_categories` INT NOT NULL,
  PRIMARY KEY (`id_produits`),
  CONSTRAINT `fk_produits_categories1`
    FOREIGN KEY (`categories_id_categories`)
    REFERENCES `ngshop`.`categories` (`id_categories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produits_categories1_idx` ON `ngshop`.`produits` (`categories_id_categories` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_nom` VARCHAR(100) NULL,
  `user_prenom` VARCHAR(100) NULL,
  `user_password` VARCHAR(255) NULL,
  `user_email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngshop`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Adresse` (
  `id_Adresse` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `Adresse_label` VARCHAR(100) NULL,
  `Adresse_num_rue` INT NULL,
  `Adresse_rue` VARCHAR(256) NULL,
  `Adresse_complement` VARCHAR(100) NULL,
  `Adresse_code_postal` INT NULL,
  `Adresse_ville` VARCHAR(50) NULL,
  `Adresse_pays` VARCHAR(45) NULL,
  `Adresse_nom` VARCHAR(100) NULL,
  `Adresse_prenom` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Adresse`),
  CONSTRAINT `fk_Adresse_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `ngshop`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Adresse_user1_idx` ON `ngshop`.`Adresse` (`user_id_user` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`promo` (
  `id_promo` INT NOT NULL AUTO_INCREMENT,
  `produits_id_produits` INT NOT NULL,
  `promo_label` VARCHAR(256) NULL,
  `promo_reduc_pourcent` INT NULL,
  `promo_new_prix` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id_promo`),
  CONSTRAINT `fk_promo_produits1`
    FOREIGN KEY (`produits_id_produits`)
    REFERENCES `ngshop`.`produits` (`id_produits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_promo_produits1_idx` ON `ngshop`.`promo` (`produits_id_produits` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`commande` (
  `id_commande` INT NOT NULL AUTO_INCREMENT,
  `commande_num_cmd` VARCHAR(10) NULL,
  `commande_date` DATE NULL,
  `user_id_user` INT NOT NULL,
  `Adresse_id_Adresse` INT NOT NULL,
  `Adresse_id_Adresse1` INT NOT NULL,
  PRIMARY KEY (`id_commande`),
  CONSTRAINT `fk_commande_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `ngshop`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_Adresse1`
    FOREIGN KEY (`Adresse_id_Adresse`)
    REFERENCES `ngshop`.`Adresse` (`id_Adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_Adresse2`
    FOREIGN KEY (`Adresse_id_Adresse1`)
    REFERENCES `ngshop`.`Adresse` (`id_Adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commande_user1_idx` ON `ngshop`.`commande` (`user_id_user` ASC);

CREATE INDEX `fk_commande_Adresse1_idx` ON `ngshop`.`commande` (`Adresse_id_Adresse` ASC);

CREATE INDEX `fk_commande_Adresse2_idx` ON `ngshop`.`commande` (`Adresse_id_Adresse1` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`produit_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`produit_commande` (
  `produits_id_produits` INT NOT NULL,
  `commande_id_commande` INT NOT NULL,
  `produit_commande_prix_unitaire` DECIMAL(5,2) NULL,
  `produit_commande_Qts` INT NULL,
  PRIMARY KEY (`produits_id_produits`, `commande_id_commande`),
  CONSTRAINT `fk_produits_commande_produits1`
    FOREIGN KEY (`produits_id_produits`)
    REFERENCES `ngshop`.`produits` (`id_produits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_commande_commande1`
    FOREIGN KEY (`commande_id_commande`)
    REFERENCES `ngshop`.`commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produits_has_commande_commande1_idx` ON `ngshop`.`produit_commande` (`commande_id_commande` ASC);

CREATE INDEX `fk_produits_has_commande_produits1_idx` ON `ngshop`.`produit_commande` (`produits_id_produits` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
