-- MySQL Script generated by MySQL Workbench
-- lun. 11 févr. 2019 16:18:23 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ngshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ngshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngshop` ;
USE `ngshop` ;

-- -----------------------------------------------------
-- Table `ngshop`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Descripion` VARCHAR(45) NULL,
  `Poids` DECIMAL(5,2) NULL,
  `Prix` DECIMAL(5,2) NULL,
  `Stock` INT NULL,
  `Image` VARCHAR(250) NULL,
  PRIMARY KEY (`idArticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngshop`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idCategorie`),
  CONSTRAINT `fk_Categorie_Article`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `ngshop`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Categorie_Article_idx` ON `ngshop`.`Categorie` (`Article_idArticle` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`Promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Promo` (
  `idPromo` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Date_de_Debut` DATETIME NULL,
  `Date_de_Fin` DATETIME NULL,
  `%_Remise` DECIMAL(2,1) NULL,
  `Prix_Remise` VARCHAR(45) NULL,
  `Article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idPromo`),
  CONSTRAINT `fk_Promo_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `ngshop`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Promo_Article1_idx` ON `ngshop`.`Promo` (`Article_idArticle` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`Adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Adress` (
  `idAdress` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Rue` VARCHAR(150) NOT NULL,
  `Complement` VARCHAR(150) NOT NULL,
  `Cp` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `Pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdress`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ngshop`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Adress_idAdress` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_User_Adress1`
    FOREIGN KEY (`Adress_idAdress`)
    REFERENCES `ngshop`.`Adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_User_Adress1_idx` ON `ngshop`.`User` (`Adress_idAdress` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(10) NOT NULL,
  `Date_de_Commande` DATETIME NOT NULL,
  `Adress_idAdress` INT NOT NULL,
  `Adress_idAdress1` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  CONSTRAINT `fk_Commande_Adress1`
    FOREIGN KEY (`Adress_idAdress`)
    REFERENCES `ngshop`.`Adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adress2`
    FOREIGN KEY (`Adress_idAdress1`)
    REFERENCES `ngshop`.`Adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ngshop`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idCommande_UNIQUE` ON `ngshop`.`Commande` (`idCommande` ASC) ;

CREATE INDEX `fk_Commande_Adress1_idx` ON `ngshop`.`Commande` (`Adress_idAdress` ASC) ;

CREATE INDEX `fk_Commande_Adress2_idx` ON `ngshop`.`Commande` (`Adress_idAdress1` ASC) ;

CREATE INDEX `fk_Commande_User1_idx` ON `ngshop`.`Commande` (`User_idUser` ASC) ;


-- -----------------------------------------------------
-- Table `ngshop`.`Commande_has_Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ngshop`.`Commande_has_Article` (
  `Commande_idCommande` INT NOT NULL,
  `Article_idArticle` INT NOT NULL,
  `Qts` INT NULL,
  `Prix` FLOAT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Article_idArticle`),
  CONSTRAINT `fk_Commande_has_Article_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `ngshop`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Article_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `ngshop`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Commande_has_Article_Article1_idx` ON `ngshop`.`Commande_has_Article` (`Article_idArticle` ASC) ;

CREATE INDEX `fk_Commande_has_Article_Commande1_idx` ON `ngshop`.`Commande_has_Article` (`Commande_idCommande` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
